export const MOVIES_RECEIVED = 'MOVIES_RECEIVED';
export const MOVIES_REQUESTED = 'MOVIES_REQUESTED';

export const POPULAR_RECEIVED = 'POPULAR_RECEIVED';
export const POPULAR_REQUESTED = 'POPULAR_REQUESTED';

export const TOP_RECEIVED = 'TOP_RECEIVED';
export const TOP_REQUESTED = 'TOP_REQUESTED';

export const UPCOMING_RECEIVED = 'UPCOMING_RECEIVED';
export const UPCOMING_REQUESTED = 'UPCOMING_REQUESTED';

export const DETAILS_RECEIVED = 'DETAILS_RECEIVED';
export const DETAILS_REQUESTED = 'DETAILS_REQUESTED';

export const CAST_CREW_RECEIVED = 'CAST_CREW_RECEIVED';
export const CAST_CREW_REQUESTED = 'CAST_CREW_REQUESTED';

export const KEYWORDS_RECEIVED = 'KEYWORDS_RECEIVED';
export const KEYWORDS_REQUESTED = 'KEYWORDS_REQUESTED';

export const SIMILAR_MOVIES_RECEIVED = 'SIMILAR_MOVIES_RECEIVED';
export const SIMILAR_MOVIES_REQUESTED = 'SIMILAR_MOVIES_REQUESTED';

export const MOVIE_IMAGES_RECEIVED = 'MOVIE_IMAGES_RECEIVED';
export const MOVIE_IMAGES_REQUESTED = 'MOVIE_IMAGES_REQUESTED';

export const MOVIE_VIDEOS_RECEIVED = 'MOVIE_VIDEOS_RECEIVED';
export const MOVIE_VIDEOS_REQUESTED = 'MOVIE_VIDEOS_REQUESTED';

export const RECOMMENDED_MOVIES_RECEIVED = 'RECOMMENDED_MOVIES_RECEIVED';
export const RECOMMENDED_MOVIES_REQUESTED = 'RECOMMENDED_MOVIES_REQUESTED';

export const MOVIE_REVIEWS_RECEIVED = 'MOVIE_REVIEWS_RECEIVED';
export const MOVIE_REVIEWS_REQUESTED = 'MOVIE_REVIEWS_REQUESTED';

export const GENRE_MOVIES_RECEIVED = 'GENRE_MOVIES_RECEIVED';
export const GENRE_MOVIES_REQUESTED = 'GENRE_MOVIES_REQUESTED';

export const PERSON_DETAILS_RECEIVED = 'PERSON_DETAILS_RECEIVED';
export const PERSON_DETAILS_REQUESTED = 'PERSON_DETAILS_REQUESTED';

export const PERSON_MOVIE_CREDITS_RECEIVED = 'PERSON_MOVIE_CREDITS_RECEIVED';
export const PERSON_MOVIE_CREDITS_REQUESTED = 'PERSON_MOVIE_CREDITS_REQUESTED';

export const MOVIES_BY_KEYWORD_RECEIVED = 'MOVIES_BY_KEYWORD_RECEIVED';
export const MOVIES_BY_KEYWORD_REQUESTED = 'MOVIES_BY_KEYWORD_REQUESTED';

export const PERSONS_RECEIVED = 'PERSONS_RECEIVED';
export const PERSONS_REQUESTED = 'PERSONS_REQUESTED';

export const DISCOVER_MOVIES_RECEIVED = 'DISCOVER_MOVIES_RECEIVED';
export const DISCOVER_MOVIES_REQUESTED = 'DISCOVER_MOVIES_REQUESTED';