export { DetailsPage } from './DetailsPage';
export { PersonPage } from './PersonPage';
export { MoviesByKeywords } from './MoviesByKeywords';
export { GenreMovies } from './GenreMovies';
export { MoviesByQuery } from './MoviesByQuery';
export { PopularMovies } from './PopularMovies';
export { TopMovies } from './TopMovies';
export { UpcomingMovies } from './UpcomingMovies';
export { PersonByQuery } from './PersonByQuery';
